[package]
name = "temporal-sdk-node"
version = "0.1.0"
authors = ["Roey Berman <roey@temporal.io>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "temporal_sdk_node"
# TODO: SJ/RB - With n-api, it should be dylib on mac, but I think needs to be cdylib on linux?
crate-type = ["cdylib"]

[dependencies]
# TODO: neon = { version = "0.7", default-features = false, features = ["napi-4"] }
neon = "0.7"

[dependencies.temporal-sdk-core]
version = "*"
path = "../../sdk-core"

[build-dependencies]
neon-build = "0.7"
